-- AlterEnum: Rename RESEARCHING to IN_CONSTRUCTION in ProspectStatus
ALTER TABLE `Prospect` MODIFY COLUMN `status` ENUM('NEW', 'RESEARCHING', 'IN_CONSTRUCTION', 'CONTACTED', 'INTERESTED', 'NOT_INTERESTED', 'READY', 'CONVERTED', 'ARCHIVED') NOT NULL DEFAULT 'NEW';

-- Migrate existing data
UPDATE `Prospect` SET `status` = 'IN_CONSTRUCTION' WHERE `status` = 'RESEARCHING';

-- Remove old enum value
ALTER TABLE `Prospect` MODIFY COLUMN `status` ENUM('NEW', 'IN_CONSTRUCTION', 'CONTACTED', 'INTERESTED', 'NOT_INTERESTED', 'READY', 'CONVERTED', 'ARCHIVED') NOT NULL DEFAULT 'NEW';

-- Same for StatusHistory.fromStatus
ALTER TABLE `StatusHistory` MODIFY COLUMN `fromStatus` ENUM('NEW', 'RESEARCHING', 'IN_CONSTRUCTION', 'CONTACTED', 'INTERESTED', 'NOT_INTERESTED', 'READY', 'CONVERTED', 'ARCHIVED') NULL;

UPDATE `StatusHistory` SET `fromStatus` = 'IN_CONSTRUCTION' WHERE `fromStatus` = 'RESEARCHING';

ALTER TABLE `StatusHistory` MODIFY COLUMN `fromStatus` ENUM('NEW', 'IN_CONSTRUCTION', 'CONTACTED', 'INTERESTED', 'NOT_INTERESTED', 'READY', 'CONVERTED', 'ARCHIVED') NULL;

-- Same for StatusHistory.toStatus
ALTER TABLE `StatusHistory` MODIFY COLUMN `toStatus` ENUM('NEW', 'RESEARCHING', 'IN_CONSTRUCTION', 'CONTACTED', 'INTERESTED', 'NOT_INTERESTED', 'READY', 'CONVERTED', 'ARCHIVED') NOT NULL;

UPDATE `StatusHistory` SET `toStatus` = 'IN_CONSTRUCTION' WHERE `toStatus` = 'RESEARCHING';

ALTER TABLE `StatusHistory` MODIFY COLUMN `toStatus` ENUM('NEW', 'IN_CONSTRUCTION', 'CONTACTED', 'INTERESTED', 'NOT_INTERESTED', 'READY', 'CONVERTED', 'ARCHIVED') NOT NULL;
